### PR TITLE
#application_command_response and #type for message

### PR DESCRIPTION
**Pull request by uscoders82**
# Summary

This PR adds the ability to check whether a message was an application command response AND adds the ability to check the type of a message.
---

## Added
~ `#type` for messages which returns the type of a message(returns integer)

~̶ ̶`̶#̶a̶p̶p̶l̶i̶c̶a̶t̶i̶o̶n̶_̶c̶o̶m̶m̶a̶n̶d̶_̶r̶e̶s̶p̶o̶n̶s̶e̶?̶`̶ ̶w̶i̶t̶h̶ ̶a̶l̶i̶a̶s̶e̶s̶ ̶`̶#̶s̶l̶a̶s̶h̶_̶c̶o̶m̶m̶a̶n̶d̶_̶r̶e̶s̶p̶o̶n̶s̶e̶?̶`̶,̶ ̶`̶#̶s̶l̶a̶s̶h̶_̶c̶o̶m̶m̶a̶n̶d̶_̶r̶e̶p̶l̶y̶?̶`̶,̶ ̶a̶n̶d̶ ̶`̶#̶a̶p̶p̶l̶i̶c̶a̶t̶i̶o̶n̶_̶c̶o̶m̶m̶a̶n̶d̶_̶r̶e̶p̶l̶y̶?̶`̶ ̶T̶h̶i̶s̶ ̶m̶e̶t̶h̶o̶d̶ ̶r̶e̶t̶u̶r̶n̶s̶ ̶a̶ ̶b̶o̶o̶l̶e̶a̶n̶ ̶s̶i̶g̶n̶i̶f̶y̶i̶n̶g̶ ̶w̶h̶e̶t̶h̶e̶r̶ ̶a̶ ̶m̶e̶s̶s̶a̶g̶e̶ ̶w̶a̶s̶ ̶a̶ ̶s̶l̶a̶s̶h̶ ̶c̶o̶m̶m̶a̶n̶d̶ ̶r̶e̶s̶p̶o̶n̶s̶e̶ ̶o̶r̶ ̶n̶o̶t̶ (changed to below:)
~`#chat_input_command?` ~~with alias `#application_command_response?`~~ This method returns a boolean signifying whether a message was of type "chat input command" or not

### CODE REVIEW

**Comment by uscoders82** [comment]
rubocop confused me and now i broke it 😶 time to make rubocop happy and with the code actually working

**Comment by swarley** [comment]
Not a fan of the `slash_command` aliases, and the `reply` aliases are a bit misleading because a reply is its own type. `chat_input_command?` may be the most correct, because it matches Discord's name for the type and context commands are also technically application command responses but occupy a separate type.

I'd like some feedback from other contributors

**Comment by uscoders82** [comment]
I changed the method name to `chat_input_command?` and gave it the alias `application_command_response?` like I had it originally. If you prefer no aliases, I can remove it.

**Comment by uscoders82** [comment]
now i removed the alias entirely

**Review by swarley — APPROVED** [review]
Thanks!

**Pull request merged**
