### PR TITLE
Add Localization Support

### PR DESCRIPTION
**Pull request by uscoders82**
# Summary

This PR adds support for application command localizations 
https://discord.com/developers/docs/interactions/application-commands#localization

## Added
~The LocalizationBuilder class
~The `.guild_locale`(with aliases `.server_locale` `.server_language` and `.guild_language`) and `.locale`(with alias `.language`) methods for interactions
~Support for creating application commands with localized names and descriptions

[locale-ex (2).txt](https://github.com/shardlab/discordrb/files/11067203/locale-ex.2.txt) This .txt file demonstrates how to register localizations and check the selected language of the invoking user

### CODE REVIEW

**Comment by uscoders82** [comment]
This PR should be ready for review once subcommand and subcommand groups can be localized 👍

**Comment by uscoders82** [comment]
I'm pretty sure all the features I planned to add are completed now, the PR is ready for review 🙂

**Comment by uscoders82** [comment]
Would an example file for slash command localizations be a good idea?

**Comment by uscoders82** [comment]
It was brought up in DAPI that a single method would be preferred for localization builders. Would the following be good? 
`.add_localization('en-GB', name_localization: 'british_name', description_localization: 'british description')`

**Comment by uscoders82** [comment]
I'm still willing to work on this, could I get feedback on what to change please?

**Comment by swarley** [comment]
> It was brought up in DAPI that a single method would be preferred for localization builders. Would the following be good? `.add_localization('en-GB', name: 'british_name', description: 'british description')`

I'm happy with this format

**Comment by uscoders82** [comment]
I have now switched everything to the preferred format, this should be all complete now.

**Comment by uscoders82** [comment]
After a battle with rubocop, the pr should now be complete

**Review by swarley — APPROVED** [review]
Thanks!

**Pull request merged**
